using CallE.Core.Domain;
using CallE.Web.Services;

namespace CallE.Tests;

/// <summary>
/// The reasoning panel reads JSON generated by an LLM: it may come back incomplete
/// or malformed. These tests guarantee the patient record never breaks
/// because of a strange response from the model.
/// </summary>
public class AgentTracePresenterTests
{
    private static AgentTrace Trace(AgentKind kind, string rawJson) => new()
    {
        Agent = kind,
        Outcome = "outcome",
        Rationale = "rationale",
        RawJson = rawJson,
        Succeeded = true,
        ElapsedMs = 1200
    };

    [Fact]
    public void ShowsQuote_AndFlagsOverride_WhenSafetyReviewRaisedRisk()
    {
        var vm = AgentTracePresenter.ToViewModel(Trace(AgentKind.DevilsAdvocate, """
            {
              "challengeFound": true,
              "overriddenRisk": "High",
              "supportingQuote": "Ahora tengo que descansar en el primer rellano",
              "missedFindings": ["ankle swelling", "orthopnea"],
              "quoteVerified": true
            }
            """));

        Assert.True(vm.RiskWasOverridden);
        Assert.Equal("Ahora tengo que descansar en el primer rellano", vm.SupportingQuote);
        Assert.Equal(2, vm.Findings.Count);
        Assert.Contains(vm.Highlights, h => h.Value == "High");
    }

    [Fact]
    public void HidesQuote_WhenItCouldNotBeVerified()
    {
        // An unverified quote did not influence the decision: it must not be shown
        // as if it were evidence.
        var vm = AgentTracePresenter.ToViewModel(Trace(AgentKind.DevilsAdvocate, """
            {
              "challengeFound": true,
              "supportingQuote": "something the patient never said",
              "quoteVerified": false
            }
            """));

        Assert.Null(vm.SupportingQuote);
        Assert.False(vm.RiskWasOverridden);
    }

    [Fact]
    public void SummarisesTrendAnalysis()
    {
        var vm = AgentTracePresenter.ToViewModel(Trace(AgentKind.TrendAnalyst, """
            {
              "trajectory": "Worsening",
              "progressiveFindings": ["decreased exercise tolerance"],
              "gradualDeteriorationDetected": true
            }
            """));

        Assert.Contains(vm.Highlights, h => h.Value == "Worsening");
        Assert.Contains(vm.Highlights, h => h.Label == "Gradual deterioration");
        Assert.Single(vm.Findings);
    }

    [Fact]
    public void SummarisesSchedulingProposal()
    {
        var vm = AgentTracePresenter.ToViewModel(Trace(AgentKind.AdaptiveScheduler,
            """{"nextCallInDays": 3, "dischargeFollowUp": false}"""));

        Assert.Contains(vm.Highlights, h => h.Value == "in 3 day(s)");
    }

    [Fact]
    public void ShowsAllFourSbarSections()
    {
        var vm = AgentTracePresenter.ToViewModel(Trace(AgentKind.ClinicalHandoff, """
            {
              "situation": "s", "background": "b",
              "assessment": "a", "recommendation": "r"
            }
            """));

        Assert.Equal(4, vm.Highlights.Count);
        Assert.Contains(vm.Highlights, h => h.Label == "Recommendation");
    }

    [Theory]
    [InlineData("")]
    [InlineData("not json at all")]
    [InlineData("{ broken json")]
    [InlineData("[1,2,3]")]
    [InlineData("""{"trajectory": 42}""")]
    public void NeverThrows_OnMalformedOrUnexpectedJson(string raw)
    {
        var vm = AgentTracePresenter.ToViewModel(Trace(AgentKind.TrendAnalyst, raw));

        // Degrades by showing the basic trace instead of crashing the page.
        Assert.Equal("outcome", vm.Outcome);
        Assert.Empty(vm.Findings);
    }

    [Fact]
    public void MapsEveryAgentToATitleAndIcon()
    {
        foreach (var kind in Enum.GetValues<AgentKind>())
        {
            var vm = AgentTracePresenter.ToViewModel(Trace(kind, "{}"));
            Assert.False(string.IsNullOrWhiteSpace(vm.Title));
            Assert.False(string.IsNullOrWhiteSpace(vm.Icon));
        }
    }
}
