using System.Text;
using System.Text.Json;

namespace CallE.Core.Services;

/// <summary>
/// Reads the real response from GET /v1/calls/{id}.
///
/// Structure confirmed against the API:
///   { id, status, summary, task_completed, completion_confidence:{score,label},
///     evidence:[...],
///     recipients:[ { status, summary, structured_result,
///                    attempts:[ { status, started_at, completed_at,
///                                 transcript_turns:[{offset_seconds,speaker,text}] } ] } ] }
/// </summary>
public static class CallStatusReader
{
    private static readonly string[] TerminalStates =
        ["completed", "failed", "cancelled", "canceled", "no_answer", "expired"];

    public static bool IsTerminal(string? state) =>
        state is not null && TerminalStates.Contains(state.ToLowerInvariant());

    /// <summary>
    /// The recipient's status is the reliable one: the task can still be "queued"
    /// while the recipient is already "in_progress" or "completed".
    /// </summary>
    public static string? ReadState(JsonElement root)
    {
        var recipient = FirstRecipient(root);

        if (recipient is { } r && r.TryGetProperty("status", out var rs) && rs.ValueKind == JsonValueKind.String)
        {
            var value = rs.GetString();
            if (!string.IsNullOrWhiteSpace(value)) return value;
        }

        return root.TryGetProperty("status", out var s) && s.ValueKind == JsonValueKind.String
            ? s.GetString()
            : null;
    }

    /// <summary>Duration computed from the attempt (the API doesn't expose it directly).</summary>
    public static int? ReadDuration(JsonElement root)
    {
        var attempt = FirstAttempt(root);
        if (attempt is not { } a) return null;

        // We prefer the last transcript offset: it reflects the actual conversation.
        if (a.TryGetProperty("transcript_turns", out var turns) && turns.ValueKind == JsonValueKind.Array)
        {
            var last = 0;
            foreach (var turn in turns.EnumerateArray())
                if (turn.TryGetProperty("offset_seconds", out var o) && o.TryGetInt32(out var v) && v > last)
                    last = v;

            if (last > 0) return last;
        }

        if (TryGetDate(a, "started_at", out var start) && TryGetDate(a, "completed_at", out var end))
        {
            var seconds = (int)(end - start).TotalSeconds;
            if (seconds > 0) return seconds;
        }

        return null;
    }

    /// <summary>Builds the transcript from transcript_turns.</summary>
    public static string ReadTranscript(JsonElement root)
    {
        var attempt = FirstAttempt(root);

        if (attempt is { } a &&
            a.TryGetProperty("transcript_turns", out var turns) &&
            turns.ValueKind == JsonValueKind.Array)
        {
            var sb = new StringBuilder();

            foreach (var turn in turns.EnumerateArray())
            {
                var text = GetString(turn, "text");
                if (string.IsNullOrWhiteSpace(text)) continue;

                // "bot" is CALL-E, "user" is the patient.
                var speaker = GetString(turn, "speaker") switch
                {
                    "bot" => "CALL-E",
                    "user" => "Patient",
                    var other => other ?? "?"
                };

                sb.AppendLine($"{speaker}: {text}");
            }

            if (sb.Length > 0) return sb.ToString().Trim();
        }

        // Without turns (e.g. voicemail) we use CALL-E's own summary.
        return ReadSummary(root) ?? string.Empty;
    }

    /// <summary>Summary generated by CALL-E; useful as additional context for our analysis.</summary>
    public static string? ReadSummary(JsonElement root)
    {
        if (FirstRecipient(root) is { } r)
        {
            var recipientSummary = GetString(r, "summary");
            if (!string.IsNullOrWhiteSpace(recipientSummary)) return recipientSummary;
        }

        return GetString(root, "summary");
    }

    /// <summary>Clues that CALL-E extracts from the call.</summary>
    public static IReadOnlyList<string> ReadEvidence(JsonElement root)
    {
        if (!root.TryGetProperty("evidence", out var evidence) || evidence.ValueKind != JsonValueKind.Array)
            return [];

        return [.. evidence.EnumerateArray()
            .Where(e => e.ValueKind == JsonValueKind.String)
            .Select(e => e.GetString()!)
            .Where(s => !string.IsNullOrWhiteSpace(s))];
    }

    /// <summary>Structured result per recipient_result_schema, if CALL-E returned one.</summary>
    public static JsonElement? ReadStructuredResult(JsonElement root)
    {
        if (FirstRecipient(root) is { } r &&
            r.TryGetProperty("structured_result", out var sr) &&
            sr.ValueKind is JsonValueKind.Object)
            return sr;

        return null;
    }

    private static JsonElement? FirstRecipient(JsonElement root)
    {
        if (root.ValueKind != JsonValueKind.Object) return null;

        if (root.TryGetProperty("recipients", out var recipients) &&
            recipients.ValueKind == JsonValueKind.Array)
            foreach (var r in recipients.EnumerateArray())
                return r;

        return null;
    }

    /// <summary>Last attempt: it reflects the outcome of the call.</summary>
    private static JsonElement? FirstAttempt(JsonElement root)
    {
        if (FirstRecipient(root) is not { } r) return null;

        if (r.TryGetProperty("attempts", out var attempts) && attempts.ValueKind == JsonValueKind.Array)
        {
            JsonElement? last = null;
            foreach (var a in attempts.EnumerateArray()) last = a;
            return last;
        }

        return null;
    }

    private static string? GetString(JsonElement element, string name) =>
        element.ValueKind == JsonValueKind.Object &&
        element.TryGetProperty(name, out var v) &&
        v.ValueKind == JsonValueKind.String
            ? v.GetString()
            : null;

    private static bool TryGetDate(JsonElement element, string name, out DateTime value)
    {
        value = default;
        var raw = GetString(element, name);
        return raw is not null && DateTime.TryParse(raw, null, System.Globalization.DateTimeStyles.AdjustToUniversal, out value);
    }
}
